name: HomingEnchantmentPlugin
version: 1.0.1
main: art.chibi.homingenchant.HomingEnchantmentPlugin
bootstrapper: art.chibi.homingenchant.HomingEnchantmentBootstrap
description: Shooting military grade homing missiles
author: dondelay
website: https://chibi.art
api-version: '1.21.4'